### PR TITLE
Adds internal documentation for `resolveMarkers` and fixes typos of `takeContent`.

### PR DESCRIPTION
**Pull request by bxff**
As the title says. 

I have struggled with understanding the code of `resolveMarkers`, it's really great code, but I think some commenting can really help someone like me understand it better, as its rather complex. Though great work!

### CODE REVIEW

**Comment by marijnh** [comment]
These are full of typos, and the "correction" isn't really necessary, so I'm going to opt to not merge them.

**Comment by bxff** [comment]
Are you open to the idea of adding internal documentation for `resolveMarkers`. Its not fully clear to me whether you just want to opt out of the typo fixes(which I am guessing is what is meant by correction), or the whole pull request. I can open another pull request for the internal documentation which fixes the typos I made before. If not, you can ignore this comment.

**Comment by marijnh** [comment]
I've added some comments in attached patch.

**Comment by bxff** [comment]
Thanks!

**Pull request closed without merging**
